### ISSUE TITLE
CameraFollowPath - Overcommenting

### ISSUE THREAD

**Issue by RichardRam87** [Calvin-Davidson/Cuphead-VerticalSlice#5]
https://github.com/Calvin-Davidson/vertical-slice/blob/development/Assets/Scripts/Camera/CameraFollowPath.cs

In deze class wordt teveel gecomment. Een variabele naam zou duidelijk genoeg moeten zijn. Gebruik comments wanneer je je gedachten en keuzeproces duidelijk wilt maken. Of wanneer je bewust van een bepaald programmeerprincipe afwijkt.

**Comment by Calvin-Davidson** [comment]
removed the unnecessary comments.
